# Generated by Django 4.2.6 on 2023-10-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
